spring.application.name=progress-study-backend
server.servlet.context-path=/progress-study-backend
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/meuprojeto?TimeZone=America/Sao_Paulo
spring.datasource.username=meudev2
spring.datasource.password=minhasenha2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR