spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=123
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5433/studytracker
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true